### ISSUE TITLE
add background icons

### ISSUE THREAD

**Issue by kristjanjansen** [kuressaareametikool/kig22-food#5]
https://www.figma.com/file/SHj51eMTSLlBRMsbVW4Upi/FOOD-TINDER?node-id=0%3A1

<img width="331" alt="Screenshot 2022-05-21 at 08 45 17" src="https://user-images.githubusercontent.com/241603/169637636-e205c496-1b89-40e2-80c5-099b45257b7a.png">

1. Export background icon(s) as SVG from Figma, start with nicest one
2. Insert on to the page (as `<img>` or pasting as source)
3. Play with https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate and https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale and https://developer.mozilla.org/en-US/docs/Web/CSS/transform
4. Figure out with @andrus14 how to move the icons to the background of the page. My tip: do not move them to background, use `pointer-events: none; opacity: 0.5` and see what happens

**Comment by andrus14** [comment]
Added apple icon.
TODO: Add two more icons.
