### ISSUE TITLE
add image with rounded corners

### ISSUE THREAD

**Issue by kristjanjansen** [kuressaareametikool/kig22-food#6]
https://www.figma.com/file/SHj51eMTSLlBRMsbVW4Upi/FOOD-TINDER?node-id=0%3A1

<img width="194" alt="Screenshot 2022-05-21 at 08 56 45 2" src="https://user-images.githubusercontent.com/241603/169638109-0fffd4ae-fa07-4728-9cad-8b656e878c72.png">

1. Pick a food image from unsplash https://unsplash.com
2. Insert an image to the page with `img` tag
3. "Fix" img tag with `display: block; width: 100%`
4. Add rounded corners with https://developer.mozilla.org/en-US/docs/Web/CSS/border-radius
5. Try add another image (more darker or lighter than first one)
6. BONUS: Experiment with lightweight shadow https://box-shadow.dev/
6. SUPERBONUS: Experiment with  https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit and https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio

**Comment by andrus14** [comment]
Solved this one in online class.
